### ISSUE TITLE
default rounding different between `est` and `est_std` labels

### ISSUE THREAD

**Issue by mattansb** [cjvanlissa/tidySEM#10]
Also could not find any way to change the number of digits - passing `digits = 3` did nothing in both cases.

``` r
library(lavaan)
#> This is lavaan 0.6-7
#> lavaan is BETA software! Please report any bugs.
library(tidySEM)

fit <- sem("mpg ~ cyl", data = mtcars)
```

rounds to 2

``` r
graph_sem(fit, label = "est")
```

![](https://i.imgur.com/lvaoCyk.png)

doesn’t round

``` r
graph_sem(fit, label = "est_std")
```

![](https://i.imgur.com/YUycd8R.png)

<sup>Created on 2020-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by albertostefanelli** [comment]
same here with the latest dev version

**Comment by cjvanlissa** [comment]
Fxed by 2d7ef2a
