### ISSUE TITLE
Renaming variables for LPA plot

### ISSUE THREAD

**Issue by follhim** [cjvanlissa/tidySEM#101]
Hello,

I think this is relatively simple, yet due to my unfamiliarity with the plot_profile output, I'm hoping to get some help. 

Essentially, I'm hoping to rename variables to be presentable (for publication) in the LPA plot that is produced from the plot_profiles() function.

```
lpa1_plot <- plot_profiles(
  lpa1_solution,
  ci = NULL,
  sd = FALSE,
  add_line = TRUE,
  rawdata = FALSE,
  bw = F
) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Here's what I have, and I've tried to do:
```
new_labels <- c(
  "var1" = "Variable 1",
  "var2" = "Variable 2",
  "var3" = "Variable 3",
  "var4" = "Variable 4",
  "var5" = "Variable 5"  
)

# Update the plot with new axis labels
lpa1_plot <- lpa1_plot +
  scale_x_discrete(labels = new_labels) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

# Display the updated plot
print(lpa1_plot)
```

Any help is appreciated thank you!
@Gootjes @cjvanlissa  do you have any experience with this?

**Comment by cjvanlissa** [comment]
It's a continuous X-axis (to allow for plotting lines etc), so your code should work but use `scale_x_continuous()` instead, e.g.:

```
plot_profiles(list(df_plot = df_plot, df_raw = NULL),
              ci = NULL, sd = FALSE, add_line = FALSE,
              rawdata = FALSE, bw = FALSE) +
  scale_x_continuous(breaks = 1, labels = "Bla")
```

**Comment by follhim** [comment]
Amazing thank you! 
For anyone looking for the new code I used:

# Create the initial plot
lpa1_plot <- plot_profiles(
  lpa1_solution,
  ci = NULL,
  sd = FALSE,
  add_line = TRUE,
  rawdata = FALSE,
  bw = FALSE
)

# Define new labels
new_labels <- c(
  "Variable 1",
  "Variable 2",
  "Variable 3",
  "Variable 4",
  "Variable 5"  
)

# Update the plot with new axis labels
lpa1_plot <- lpa1_plot +
  scale_x_continuous(
    breaks = 1:5,  # Assuming you have 5 variables
    labels = new_labels
  )
