### ISSUE TITLE
avoid overlapping labels

### ISSUE THREAD

**Issue by mattansb** [cjvanlissa/tidySEM#16]
Is there any way to shift the labels along the edges?

In this example, they are overlapping and only one can be seen:

``` r
library(tidySEM)
library(lavaan)

mod <- "
mpg ~ am + cyl
hp ~ am + cyl
"

fit <- sem(mod, data = mtcars)


lay <- get_layout(
  "cyl", "mpg",
  NA, NA,
  "am", "hp",
  rows = 3
)

graph_sem(fit, layout = lay)
```

![](https://i.imgur.com/RMeqwn8.png)

<sup>Created on 2021-03-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by cjvanlissa** [comment]
Yes, using the argument `label_location`. Is this not documented?

Bwt, could you get in touch with me on c.j.vanlissa at uu dot nl? I have added new experimental features for standard editing jobs, like making all non-significant paths gray, or removing all variance arrows, etc. I'm not ready to release this version, but perhaps you might be interested in testing it!

**Comment by cjvanlissa** [comment]
E.g. 

```
library(tidySEM)
library(lavaan)
library(dplyr)

mod <- "
mpg ~ am + cyl
hp ~ am + cyl
"

fit <- sem(mod, data = mtcars)


lay <- get_layout(
  "cyl", "mpg",
  NA, NA,
  "am", "hp",
  rows = 3
)

prepare_graph(fit, layout = lay) %>%
  hide_var() %>%
  hide_fixed() %>%
  edit_graph({label_location = .2}) %>%
  plot()
```

![image](https://user-images.githubusercontent.com/11941251/109619356-fabce300-7b38-11eb-98bf-80041669337e.png)

**Comment by mattansb** [comment]
Ohh... that looks cool!

Thanks!
