### ISSUE TITLE
add column with modifier names

### ISSUE THREAD

**Issue by mattansb** [cjvanlissa/tidySEM#18]
```r
library(tidySEM)
library(lavaan)

fit <- sem("mpg ~ a * am", data = mtcars)

get_edges(fit, digits = 1)
#>   from  to arrow   label lhs op rhs  est  se pval      confint est_sig est_std se_std pval_std confint_std est_sig_std
#> 1   am mpg  last  7.2*** mpg  ~  am  7.2 1.7  0.0  [3.9, 10.6]  7.2***     0.6    0.1      0.0  [0.4, 0.8]      0.6***
#> 2  mpg mpg  both 22.5*** mpg ~~ mpg 22.5 5.6  0.0 [11.5, 33.6] 22.5***     0.6    0.1      0.0  [0.4, 0.9]      0.6***
#> 3   am  am  both     0.2  am ~~  am  0.2 0.0 <NA>   [0.2, 0.2]     0.2     1.0    0.0     <NA>  [1.0, 1.0]         1.0
```

I'd expect to also see the `"a"` modifier somewhere.

**Comment by cjvanlissa** [comment]
The column is called 'label', and is thus masked by the tidySEM label. What would be an appropriate solution?

**Comment by mattansb** [comment]
I think maybe "modifier" or "modifier_label"?

**Comment by cjvanlissa** [comment]
I've renamed the mplus labels to `mplus_label` and the lavaan labels to `lavaan_label`, retaining the name `label` for the printed labels in `sem_graph()`

**Comment by mattansb** [comment]
Awesome! Thanks!
![image](https://user-images.githubusercontent.com/35330040/110206349-ca9d7900-7e85-11eb-9dfc-812cd4b875a1.png)
