### ISSUE TITLE
Are multilevel models supported in graph_sem()? [Question]

### ISSUE THREAD

**Issue by albertostefanelli** [cjvanlissa/tidySEM#29]
Hi, 

Thanks for this fantastic package. I am using tidySEM to teach a multilevel SEM and I was wondering if the graph_sem() function support multilevel models from Mplus.

**Comment by cjvanlissa** [comment]
Note that `semPaths()` is a function from the `semPlot` package. My function `graph_sem()` should "just work" for multilevel Mplus models, but if you find an error do let me know and I'll debug it with you.

**Comment by albertostefanelli** [comment]
Indeed, I was referring to graph_sem(). very sorry for the typo. 
Using a basic Mplus example, the function returns

` graph_sem(model = my_model) 
  Argument 'layout' must be a matrix or data.frame. `

**Comment by cjvanlissa** [comment]
I think perhaps you don't have the latest development version, and might be feeding the function the output of mplusModeler(). Could you try

```
remotes::install_github("cjvanlissa/tidySEM")
```

And then try again?

Or otherwise 

```
graph_sem(my_model$results)
```

**Comment by albertostefanelli** [comment]
Replication for this issue. I might be getting something wrong in the code.
Mplus 8.4 is used 
[replication_tidySEM_graph_sem.html.zip](https://github.com/cjvanlissa/tidySEM/files/6197660/replication_tidySEM_graph_sem.html.zip)

**Comment by cjvanlissa** [comment]
Thank you! I'm on it!

**Comment by cjvanlissa** [comment]
@albertostefanelli you were right, there were bugs. I've fixed get_nodes() and get_layout() for multilevel models. There is one thing not working quite right: The default connect_from and connect_to settings. This is super difficult to fix in the package (the ideal solution requires some physics; connector points should repel one another), but very easy to customize in your own plot.

**Comment by albertostefanelli** [comment]
This is excellent. Thanks so much! 
I noticed that the arrow heads at the between level are not displayed. Not sure if this is related to what you mentioned in your comment. 

I also have an additional question: Is there the possibility to plot mediation models such as there is an overall model and not a between and within part ?

**Comment by cjvanlissa** [comment]
Dear Alberto, indeed, this is related to my comment. The arrow heads are displayed, but because the connection algorithm places the connection on the wrong side of the node, they are not visible until you customize the connection locations. This is hard to fix in the package, but easy to customize in your plot.

Yes, you can visualize mediation models of course.
