### ISSUE TITLE
Re-implement BLRT?

### ISSUE THREAD

**Issue by cjvanlissa** [cjvanlissa/tidySEM#41]
BLRT is unfeasibly slow.

**Comment by cjvanlissa** [comment]
ps.
1. Initially estimate the k  1 and k class models to provide the likelihoods
for calculating the 2

log likelihood difference.
2. Under the null k1 class model, generate a bootstrap sample and calculate
the 2

log likelihood difference between the k  1 and k class models.
3. Repeat this process independently many times and estimate the true distribution of the 2

log likelihood difference.
4. Estimate the p value by comparing the distribution obtained in Step 3 with
the 2

log likelihood difference obtained in Step 1. This p value is then
used to determine if the null k 1 class model should be rejected in favor
of the

**Comment by haozhou1988** [comment]
I am a little confused by the second step of generating a bootstrap sample. Does it mean simulating a new dataset from the null model or resampling the data from the original data set?  mirt::boot.LR function seems to generate a new dataset from the null model.

**Comment by cjvanlissa** [comment]
> mirt::boot.LR function seems to generate a new dataset from the null model.

Exactly, that echoes what is said above! Simulate a dataset from the k-1 model (which is the null model when testing k-1 vs k)!

There is a function `tidySEM::BLRT()` that does this, but it's extremely slow and inefficient. It usually crashes my computer. We are working on a better alternative.
