### ISSUE TITLE
Can we control the line size by standardized coeffiecent?

### ISSUE THREAD

**Issue by womeimingzi11** [cjvanlissa/tidySEM#51]
As mentioned by the title, I am not sure whether this function has been implemented or not.

I find there is a function `size_sig(data, size = 1, ...)`, but it looks can not control size of each arrow.

This will make the picture clearer to understand and discover the most important relationships. Just like the following figures.

![CleanShot 2022-05-31 at 14 36 50](https://user-images.githubusercontent.com/10340253/171108492-bd41abee-f9f3-47ec-ab60-cba4321aa570.jpeg)

**Comment by dorinstanciu** [comment]
I would also be interested in the line thickness in general; I read the documentation (and found indications about the size of elements) but couldn't find anything specific about line thickness, as in for variance/covariance or regression lines (maybe it's just me being dumb). Thanks!
