### ISSUE TITLE
table_results(): Separating est from sig

### ISSUE THREAD

**Issue by sda030** [cjvanlissa/tidySEM#54]
Regardin table_results(), I would prefer estimate to be separated from sig. It is usually easier to unite them manually afterwards rather than having to separate them, which is non-trivial given that there is no clear separator or position. Same applies to confint, which is according to tidymodels-principles (i.e. broom) separated. Moreover, although some use APA-style, one may want to set styles downstream, for instance using the gt-package.

EDIT: Also the label column could also benefit from consistently splitting paramHeader from param (in MplusAutomation-jargon), which would simplify downstream extraction of loadings, variances, etc. Will also be easier to implement later some prettifier-functions to convert "loadings" to a lambda-character, etc.

**Comment by sda030** [comment]
Ah, I did not realize until now that one could still set the argument ```columns = c("est", "se")```, so ignore that point. I would clarify this in the documentation though.

**Comment by cjvanlissa** [comment]
What columns are available depends on the estimation software and type of analysis. Since `"se"` is not always available, I don't want to hard-code that into the documentation. The first lines of the documentation are:

```
A character vector of columns to retain from the results
#' section. If this is set to \code{NULL}, all available columns are returned.
```
