### ISSUE TITLE
Unable to calculate sum scores using create_scales()?

### ISSUE THREAD

**Issue by ghost** [cjvanlissa/tidySEM#57]
Hi,

I see in the documentation that the create_scales function should allow for the calculation of either mean or sum scores -- it seems that the default is mean, so how would you go about calculating sum scores instead? I've tried adding several arguments from the psych package (e.g., totals = TRUE) to the function, but I'm still getting mean scores.

Thanks!

**Comment by cjvanlissa** [comment]
Thanks for flagging this, `...` was not passed on. It should work with the commit I'm pushing now!
