### ISSUE TITLE
miss-matched defaults from `graph_sem` and `get_edges`

### ISSUE THREAD

**Issue by mattansb** [cjvanlissa/tidySEM#6]
`graph_sem()` seems to plot the unstandardized parameter, 
while `get_edges()` gets the standerdized parameters.

So we get:

``` r
library(lavaan)
#> This is lavaan 0.6-6
#> lavaan is BETA software! Please report any bugs.
library(tidySEM)

res <- sem("dist ~ speed", cars)

graph_sem(res)
```

![](https://i.imgur.com/HEoiEbU.png)

``` r

graph_sem(res, edges = get_edges(res))
```

![](https://i.imgur.com/dJRbZbX.png)

<sup>Created on 2020-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Which seems like an odd behavior.

I'd expect:
1. `get_edges()` to return various values (est, est_sig, std, std_sig, sig... or something like that)
2. `graph_sem()` to have a `label_edge` argument to choose the labels of the edges from the result of `get_edges()`.

I guess this would need a complimentary `label_node` argument to choose the labels of the nodes from the result of `get_nodes()`.
(Instead of `label`, which is documented as controlling the label of the nodes, but actually seems to control the labels of the edges?)

**Comment by mattansb** [comment]
This is resolved with the latest update - thanks!

``` r
library(lavaan)
#> This is lavaan 0.6-7
#> lavaan is BETA software! Please report any bugs.
library(tidySEM)

res <- sem("dist ~ speed", cars)


graph_sem(res)
```

![](https://i.imgur.com/zecfvRE.png)

``` r
graph_sem(res, edges = get_edges(res))
```

![](https://i.imgur.com/wKrT9j6.png)

``` r


graph_sem(res, label = "est_sig_std")
```

![](https://i.imgur.com/H0L7JBt.png)

``` r
graph_sem(res, edges = get_edges(res, label = "est_sig_std"))
```

![](https://i.imgur.com/oDvX5on.png)

<sup>Created on 2020-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cjvanlissa** [comment]
@mattansb thank you for debugging this, it was very helpful!

**Comment by mattansb** [comment]
@cjvanlissa I will be using this for teaching in the spring semester - great stuff! Thanks!
