### ISSUE TITLE
Example of BCH with distal outcomes

### ISSUE THREAD

**Issue by DanBennettDev** [cjvanlissa/tidySEM#68]
Hi,
it's great to see that tidySEM offers a way of running latent profile analyses using BCH. At present in there don't seem to be other robust methods to relate LPA groups to distal outcomes in R or non-proprietary software. This could make a real contribution to open science around these techniques.

At present though the example for BCH is quite minimal, showing an intercept only model. Is there any chance of providing a more representative example, e.g. multivariate, and linking groups to distal outcomes.

**Comment by cjvanlissa** [comment]
Yes, this is already done but I haven't pushed the update. Please see cjvanlissa.github.io/tidySEM now for the new vignettes!

**Comment by DanBennettDev** [comment]
Ah, fantastic - I've only had a quick glance, but those tutorials look great. 
This is a really fantastic contribution :)
