### ISSUE TITLE
Instruction on modifying syntax

### ISSUE THREAD

**Issue by midryoun** [cjvanlissa/tidySEM#80]
Hi,

I'd like to report an instruction on the GitHub page that could be incomplete depending on circumstances.

On [this page](https://cjvanlissa.github.io/tidySEM/articles/Generating_syntax.html#optional-step-6-modify-the-dictionary-and-syntax), an example was provided to illustrate how to modify syntax that combind two latent variables into one.

<img width="642" alt="image" src="https://github.com/cjvanlissa/tidySEM/assets/70600836/d9aee886-515e-434b-b36a-eafb1ef17d11">

However, the provided code does not alter "free" and "ustart" values, which in turn will end up the latent variable "tex" to have two reference indicators. Usually this is not a desired modification when you combine two factors. 

<img width="318" alt="image" src="https://github.com/cjvanlissa/tidySEM/assets/70600836/4d5fb681-fe51-4ec2-b016-51dcee663b65">

If one wants only one reference indicator on their combined factor, one should include additional code that looks like:

mutate(free = ifelse(rhs == "spe_1", 1, free),
         ustart = ifelse(rhs == "spe_1", NA, ustart))

It would be nice if the instruction mentions this. Thank you for a great package!

**Comment by cjvanlissa** [comment]
Good point, I'm on it!
