### ISSUE TITLE
Missing data issue? Latent profile analysis

### ISSUE THREAD

**Issue by follhim** [cjvanlissa/tidySEM#98]
Hello I'm reaching out today because I am having issues running an LPA model(s). 
When I remove NAs from the data, the model runs fine, but ofc that is a problem as we want to use what we can. From my understanding, `mx_profiles()` SHOULD use FIML automatically, but somehow that does not seem to be the case.

Now to be fair, three of the five variables are ordinal, but I want it to be treated as continuous (which is not an uncommon practice). 
However this is the error message I get:

lpa_data <- subset(data, select = c(sexualidentitysalience, lgbtconnect, relcom, serviceattendance, nora))
> lpa_data <- sapply(lpa_data, as.numeric)
> lpa_data <- as.data.frame(lpa_data)
> res <- mx_profiles(data = lpa_data, classes = 1:6)
Running mix1 with 10 parameters
Could not initialize clusters using K-means, switching to hierarchical clustering.
Error in tidySEM:::mixture_starts(model = new("MxModel", name = "mix2",  : 
  Could not initialize clusters using hierarchical clustering. Consider using a different clustering method, or imputing missing data.

TidyLPA does not allow for FIML, which is why I'm hoping to use the all powerful TidySEM. If anyone can please help, I would greatly appreciate it!

**Comment by cjvanlissa** [comment]
The model is not able to automatically determine starting values. Conducting a preliminary analysis on only complete cases, and using the resulting parameters as starting values for FIML with partially missing data, will likely solve your problem.

**Comment by follhim** [comment]
Thank you! How could I then use the resulting parameters as starting values for FIML?

I also have two questions related to auxiliary analyses, particularly covariates and distal outcomes.
I understand that BCH() essentially performs the 3-step approach, but I'm confused about how it approaches covariates and distal outcomes. 

For instance:
How does one predict class membership (of the given data)?
I know it's frowned upon to use multinomial regression since it does take into account error or the actual likelihood of class assignment. I was looking at the vignettes you provided and was unclear exactly what you were referring to. 
Is these the right?
```
covariates_model <- BCH(lpa1_solution, 
                        model = "class ~ education + age", 
                        data = lpa1_data)
summary(covariates_model)
```
**Distal Outcomes**
```
BCH(lpa1_solution, data = lpa1_data$dep) %>%
  lr_test()
```
Thank you! I've loved using TidySEM so far, and this offers a lot of things that tidyLPA doesn't!

**Comment by cjvanlissa** [comment]
Dear @follhim , unfortunately a lot of this just comes down to reading the documentation of OpenMx and tidySEM, and I can't give that kind of support! Maybe I'll record some instructional videos over the summer but can't promise anything

**Comment by Gootjes** [comment]
I wrote a similar analysis in R follhim!  I can share the code with you. I
did it slightly differently than CJ suggested, as his approach assumes MCAR
for the starting values, which may be totally fine, depending on your
situation. I did an inspiration using the mice package to generate a
complete dataset for the starting values, and then substitute the data with
missings back in for the actual estimating process.

For a subsequent analysis i used multinomial regression using a new
function in the tidy sem package which allows you to include the class
probabilities as uncertainty in the model via a logic akin to imputation.

Op ma 1 jul 2024 13:03 schreef C. J. van Lissa ***@***.***>:

**Comment by cjvanlissa** [comment]
@Gootjes since you already did this, maybe we can turn it into a vignette? I would be happy to collaborate on that.

**Comment by follhim** [comment]
This is amazing-I would love if you could share your code!

Thank you so much!

-----
Seungju Kim
Wheaton College, BA 23'

**Comment by follhim** [comment]
I hear you. If you do make a video please let me know!

-----
Seungju Kim
Wheaton College, BA 23'

**Comment by follhim** [comment]
@Gootjes Hello,
I wanted to follow up and ask if you would be so kind to share the syntax you used to perform your analyses. I'm currently working on a manuscript on this, and would love any insights with your materials. 

Thank you!

**Comment by Gootjes** [comment]
> @Gootjes Hello, I wanted to follow up and ask if you would be so kind to share the syntax you used to perform your analyses. I'm currently working on a manuscript on this, and would love any insights with your materials.
> 
> Thank you!

@follhim 
Here is an R snippet to help you out. If anything is unclear let me know and I will help you further!
```r
library(tidySEM)
data("empathy")

df_complete <- empathy[1:6]

# Simulate missingness because I don't have a shareable dataset with missingness available
missingness_types <- c("0" = .30, "1" = .20, "2" = .20, "3" = .15, "4" = .10, "5" = .05)
stopifnot(sum(missingness_types) == 1)

set.seed(1337)
random_missingness_type <- sample(x = 0:5, size = nrow(df_complete), replace = TRUE, prob = missingness_types)

df_missing <- df_complete
for(i in 1:nrow(df_missing)) {
  miss <- sample(x = 1:6, size = random_missingness_type[[i]], replace = FALSE)
  df_missing[i, miss] <- NA
}

# This is the analysis on the complete dataset, for comparison purposes
mx_profiles(data = df_complete,
            classes = 2) -> model_complete_result

# This is the analysis on the dataset with missingness

## First step: impute the dataset
df_imputed <- mice::complete(mice::mice(df_missing, m = 1))


## Second step: use this imputed dataset for starting values
mx_profiles(data = df_imputed,
            classes = 2,
            run = FALSE) -> model_starting_values

## Copy over the starting values by swapping out the dataset for the one with missing values
final_model <- mxModel(model_starting_values, mxData(observed = df_missing, type = "raw"))

## Run the model
final_model_result <- run_mx(final_model)

# Follow-up analysis
df_dv <- cbind(df_missing, pt1 = empathy[,"pt1"])

tidySEM::pseudo_class(x = final_model_result, model = lm(pt1 ~ class, data = data), data = df_dv)


tidySEM::pseudo_class(x = final_model_result, model = function(data) {
  # multinom needs a patch because there is currently an issue with the implementation
  m <- nnet::multinom(class ~ pt1, data = data)
  class(m) <- head(class(m), 1)
  m
}, data = df_dv)
```

**Comment by follhim** [comment]
Hi @Gootjes, Apologies, I never got to thank you for your incredibly helpful response. Thank you!
